# Generated by Django 4.2.7 on 2024-04-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_app", "0002_delete_pricemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=100)),
            ],
        ),
    ]
