# Generated by Django 4.2.7 on 2024-04-01 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceModel",
        ),
    ]
