# Generated by Django 4.2.7 on 2024-02-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('Laundry', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('clothes', models.CharField(max_length=100)),
                ('number_baskets', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
