# Generated by Django 4.2.7 on 2024-02-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelForm',
        ),
    ]
