# Generated by Django 4.2.7 on 2024-02-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_service', '0006_alter_modelform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
