# Generated by Django 4.2.7 on 2024-03-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_service', '0008_remove_modelform_number_modelform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform',
            name='number_clothes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelform',
            name='number_baskets',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
