# Generated by Django 4.2.7 on 2024-03-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_service', '0009_modelform_number_clothes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform',
            name='status',
            field=models.CharField(choices=[('1', 'เสร็จเเล้ว'), ('2', 'รอการส่งซัก'), ('3', 'รอการส่งซัก')], default=1, max_length=255),
        ),
    ]
