# Generated by Django 4.2.7 on 2024-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_service", "0010_modelform_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelform",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "เสร็จเเล้ว"),
                    ("2", "ยังไม่เสร็จ"),
                    ("3", "รอการส่งซัก"),
                ],
                default=3,
                max_length=255,
            ),
        ),
    ]
