# Generated by Django 4.2.7 on 2024-04-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_service", "0013_alter_modelform_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelform",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "เสร็จเเล้ว"),
                    ("2", "ยังไม่เสร็จ"),
                    ("3", "รอการส่งซัก"),
                    ("4", "ยกเลิกเเล้ว"),
                ],
                default="3",
                max_length=255,
            ),
        ),
    ]
