# Generated by Django 4.2.7 on 2024-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_service", "0014_alter_modelform_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelform",
            name="admin_price",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
