# Generated by Django 4.2.7 on 2024-07-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_service', '0015_modelform_admin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='status',
            field=models.CharField(choices=[('1', 'เสร็จเเล้ว'), ('2', 'กำลังดำเนินการ'), ('3', 'รอการส่งซัก'), ('4', 'ยกเลิกเเล้ว')], default='3', max_length=255),
        ),
    ]
