# Generated by Django 4.2.7 on 2024-02-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_rename_userprofile_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
